# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(896, 694)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(MainWin)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gbxOpType = QtWidgets.QGroupBox(self.groupBox)
        self.gbxOpType.setObjectName("gbxOpType")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxOpType)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rabAdd = QtWidgets.QRadioButton(self.gbxOpType)
        self.rabAdd.setObjectName("rabAdd")
        self.horizontalLayout.addWidget(self.rabAdd)
        self.rabSub = QtWidgets.QRadioButton(self.gbxOpType)
        self.rabSub.setObjectName("rabSub")
        self.horizontalLayout.addWidget(self.rabSub)
        self.rabMult = QtWidgets.QRadioButton(self.gbxOpType)
        self.rabMult.setObjectName("rabMult")
        self.horizontalLayout.addWidget(self.rabMult)
        self.rabDiv = QtWidgets.QRadioButton(self.gbxOpType)
        self.rabDiv.setObjectName("rabDiv")
        self.horizontalLayout.addWidget(self.rabDiv)
        self.horizontalLayout_4.addWidget(self.gbxOpType)
        self.gbxOpStep = QtWidgets.QGroupBox(self.groupBox)
        self.gbxOpStep.setObjectName("gbxOpStep")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gbxOpStep)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rabOneStep = QtWidgets.QRadioButton(self.gbxOpStep)
        self.rabOneStep.setObjectName("rabOneStep")
        self.horizontalLayout_2.addWidget(self.rabOneStep)
        self.rabTwoStep = QtWidgets.QRadioButton(self.gbxOpStep)
        self.rabTwoStep.setObjectName("rabTwoStep")
        self.horizontalLayout_2.addWidget(self.rabTwoStep)
        self.ranTreeStep = QtWidgets.QRadioButton(self.gbxOpStep)
        self.ranTreeStep.setObjectName("ranTreeStep")
        self.horizontalLayout_2.addWidget(self.ranTreeStep)
        self.horizontalLayout_4.addWidget(self.gbxOpStep)
        self.gbxSubjectType = QtWidgets.QGroupBox(self.groupBox)
        self.gbxSubjectType.setObjectName("gbxSubjectType")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbxSubjectType)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rabResult = QtWidgets.QRadioButton(self.gbxSubjectType)
        self.rabResult.setObjectName("rabResult")
        self.horizontalLayout_3.addWidget(self.rabResult)
        self.rabItem = QtWidgets.QRadioButton(self.gbxSubjectType)
        self.rabItem.setObjectName("rabItem")
        self.horizontalLayout_3.addWidget(self.rabItem)
        self.horizontalLayout_4.addWidget(self.gbxSubjectType)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(MainWin)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnOpResSet = QtWidgets.QPushButton(self.groupBox_6)
        self.btnOpResSet.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpResSet.setObjectName("btnOpResSet")
        self.horizontalLayout_5.addWidget(self.btnOpResSet)
        self.btnOperatorSet = QtWidgets.QPushButton(self.groupBox_6)
        self.btnOperatorSet.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOperatorSet.setObjectName("btnOperatorSet")
        self.horizontalLayout_5.addWidget(self.btnOperatorSet)
        self.horizontalLayout_6.addWidget(self.groupBox_6)
        self.ckbBracket = QtWidgets.QCheckBox(self.groupBox_5)
        self.ckbBracket.setObjectName("ckbBracket")
        self.horizontalLayout_6.addWidget(self.ckbBracket)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gbxAddSet = QtWidgets.QGroupBox(MainWin)
        self.gbxAddSet.setObjectName("gbxAddSet")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.gbxAddSet)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rabRandCarry = QtWidgets.QRadioButton(self.gbxAddSet)
        self.rabRandCarry.setObjectName("rabRandCarry")
        self.horizontalLayout_7.addWidget(self.rabRandCarry)
        self.rabAddCarry = QtWidgets.QRadioButton(self.gbxAddSet)
        self.rabAddCarry.setObjectName("rabAddCarry")
        self.horizontalLayout_7.addWidget(self.rabAddCarry)
        self.rabNoCarry = QtWidgets.QRadioButton(self.gbxAddSet)
        self.rabNoCarry.setObjectName("rabNoCarry")
        self.horizontalLayout_7.addWidget(self.rabNoCarry)
        self.horizontalLayout_11.addWidget(self.gbxAddSet)
        self.gbxSubSet = QtWidgets.QGroupBox(MainWin)
        self.gbxSubSet.setObjectName("gbxSubSet")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.gbxSubSet)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rabRandAbdicate = QtWidgets.QRadioButton(self.gbxSubSet)
        self.rabRandAbdicate.setObjectName("rabRandAbdicate")
        self.horizontalLayout_8.addWidget(self.rabRandAbdicate)
        self.rabSubAbdicate = QtWidgets.QRadioButton(self.gbxSubSet)
        self.rabSubAbdicate.setObjectName("rabSubAbdicate")
        self.horizontalLayout_8.addWidget(self.rabSubAbdicate)
        self.rabNoAbdicate = QtWidgets.QRadioButton(self.gbxSubSet)
        self.rabNoAbdicate.setObjectName("rabNoAbdicate")
        self.horizontalLayout_8.addWidget(self.rabNoAbdicate)
        self.horizontalLayout_11.addWidget(self.gbxSubSet)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.groupBox_9 = QtWidgets.QGroupBox(MainWin)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.groupBox_9)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.spbSubjectCount = QtWidgets.QSpinBox(self.groupBox_9)
        self.spbSubjectCount.setMinimumSize(QtCore.QSize(0, 22))
        self.spbSubjectCount.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spbSubjectCount.setMinimum(1)
        self.spbSubjectCount.setMaximum(999)
        self.spbSubjectCount.setObjectName("spbSubjectCount")
        self.horizontalLayout_9.addWidget(self.spbSubjectCount)
        self.btnAddSubject = QtWidgets.QPushButton(self.groupBox_9)
        self.btnAddSubject.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAddSubject.setObjectName("btnAddSubject")
        self.horizontalLayout_9.addWidget(self.btnAddSubject)
        self.btnClearSubject = QtWidgets.QPushButton(self.groupBox_9)
        self.btnClearSubject.setMinimumSize(QtCore.QSize(0, 30))
        self.btnClearSubject.setObjectName("btnClearSubject")
        self.horizontalLayout_9.addWidget(self.btnClearSubject)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(MainWin)
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.txbContent = QtWidgets.QTextBrowser(self.groupBox_10)
        self.txbContent.setObjectName("txbContent")
        self.horizontalLayout_10.addWidget(self.txbContent)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(MainWin)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout.setObjectName("gridLayout")
        self.lneSubTitle = QtWidgets.QLineEdit(self.groupBox_11)
        self.lneSubTitle.setMinimumSize(QtCore.QSize(0, 22))
        self.lneSubTitle.setObjectName("lneSubTitle")
        self.gridLayout.addWidget(self.lneSubTitle, 1, 5, 1, 3)
        self.spbColCount = QtWidgets.QSpinBox(self.groupBox_11)
        self.spbColCount.setMinimumSize(QtCore.QSize(0, 22))
        self.spbColCount.setMinimum(1)
        self.spbColCount.setMaximum(5)
        self.spbColCount.setObjectName("spbColCount")
        self.gridLayout.addWidget(self.spbColCount, 0, 4, 1, 1)
        self.btnBrowse = QtWidgets.QPushButton(self.groupBox_11)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout.addWidget(self.btnBrowse, 0, 7, 1, 1)
        self.spbTotal = QtWidgets.QSpinBox(self.groupBox_11)
        self.spbTotal.setMinimumSize(QtCore.QSize(60, 22))
        self.spbTotal.setObjectName("spbTotal")
        self.gridLayout.addWidget(self.spbTotal, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_11)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.lneOutPath = QtWidgets.QLineEdit(self.groupBox_11)
        self.lneOutPath.setObjectName("lneOutPath")
        self.gridLayout.addWidget(self.lneOutPath, 0, 6, 1, 1)
        self.lneTitle = QtWidgets.QLineEdit(self.groupBox_11)
        self.lneTitle.setMinimumSize(QtCore.QSize(0, 22))
        self.lneTitle.setObjectName("lneTitle")
        self.gridLayout.addWidget(self.lneTitle, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.groupBox_11)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_11)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_11)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_11)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_11)
        self.btnGen = QtWidgets.QPushButton(MainWin)
        self.btnGen.setMinimumSize(QtCore.QSize(0, 35))
        self.btnGen.setObjectName("btnGen")
        self.verticalLayout.addWidget(self.btnGen)

        self.retranslateUi(MainWin)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "MainWin"))
        self.groupBox.setTitle(_translate("MainWin", "题型选择"))
        self.gbxOpType.setTitle(_translate("MainWin", "运算类型选择"))
        self.rabAdd.setText(_translate("MainWin", "加法"))
        self.rabSub.setText(_translate("MainWin", "减法"))
        self.rabMult.setText(_translate("MainWin", "乘法"))
        self.rabDiv.setText(_translate("MainWin", "除法"))
        self.gbxOpStep.setTitle(_translate("MainWin", "几步运算"))
        self.rabOneStep.setText(_translate("MainWin", "一步"))
        self.rabTwoStep.setText(_translate("MainWin", "二步"))
        self.ranTreeStep.setText(_translate("MainWin", "三步"))
        self.gbxSubjectType.setTitle(_translate("MainWin", "题目类型"))
        self.rabResult.setText(_translate("MainWin", "求结果"))
        self.rabItem.setText(_translate("MainWin", "求算数项"))
        self.groupBox_5.setTitle(_translate("MainWin", "详细设置"))
        self.groupBox_6.setTitle(_translate("MainWin", "运算项结果符合设置"))
        self.btnOpResSet.setText(_translate("MainWin", "运算项及结果范围设置"))
        self.btnOperatorSet.setText(_translate("MainWin", "运算符号设置"))
        self.ckbBracket.setText(_translate("MainWin", "使用括号"))
        self.gbxAddSet.setTitle(_translate("MainWin", "加法设置"))
        self.rabRandCarry.setText(_translate("MainWin", "随机进位"))
        self.rabAddCarry.setText(_translate("MainWin", "加法进位"))
        self.rabNoCarry.setText(_translate("MainWin", "没有进位"))
        self.gbxSubSet.setTitle(_translate("MainWin", "减法设置"))
        self.rabRandAbdicate.setText(_translate("MainWin", "随机退位"))
        self.rabSubAbdicate.setText(_translate("MainWin", "减法退位"))
        self.rabNoAbdicate.setText(_translate("MainWin", "没有退位"))
        self.groupBox_9.setTitle(_translate("MainWin", "添加计算题到试卷"))
        self.label.setText(_translate("MainWin", "题目个数："))
        self.btnAddSubject.setText(_translate("MainWin", "添加题目"))
        self.btnClearSubject.setText(_translate("MainWin", "清空题目"))
        self.groupBox_10.setTitle(_translate("MainWin", "当前试卷包含题目："))
        self.groupBox_11.setTitle(_translate("MainWin", "试卷设置"))
        self.btnBrowse.setText(_translate("MainWin", "浏览"))
        self.label_3.setText(_translate("MainWin", "试卷列量："))
        self.label_2.setText(_translate("MainWin", "生成试卷数量："))
        self.label_5.setText(_translate("MainWin", "试卷副标题："))
        self.label_6.setText(_translate("MainWin", "输出目录："))
        self.label_4.setText(_translate("MainWin", "试卷标题："))
        self.btnGen.setText(_translate("MainWin", "开始生成试卷"))

